package skip.kit

import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.saveable.Saver
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.runtime.setValue
import skip.lib.*
import skip.lib.Array

// Copyright 2025–2026 Skip
// SPDX-License-Identifier: MPL-2.0
import skip.foundation.*
import skip.ui.*
import skip.model.*

/// A "Software Bill of Materials" view that displays the third-party software dependencies
/// of the host app, parsed from SPDX SBOM resource files in the given bundle.
///
/// The view looks for SBOM resources generated by `skip sbom create`:
///
/// - On Apple platforms: `sbom-darwin-ios.spdx.json`
/// - On Android: `sbom-linux-android.spdx.json`
///
/// Each dependency is presented as a row showing its name, supplier, version, and declared
/// license. Tapping a row navigates to a detail view that shows all SPDX fields for the
/// package, including checksums and external references. Where the declared license is a
/// recognised SPDX identifier (e.g., `EUPL-1.2`, `Apache-2.0`), the detail view exposes a
/// button that opens the corresponding page on https://spdx.org/licenses/ in an in-app
/// browser, so users can review the full license text.
///
/// The list also includes a button that brings up the system share sheet so users can
/// export the raw SPDX JSON for offline review or auditing.
///
/// `SBOMView` is intended to be dropped into a Settings or Preferences view via a
/// `NavigationLink`:
///
/// ```swift
/// NavigationLink("Bill of Materials") {
///     SBOMView(bundle: Bundle.module)
/// }
/// ```
///
/// This view exists in part to comply with open-source license obligations that require
/// distributing apps to mention the licenses of included software.
@androidx.annotation.Keep
class SBOMView: View, skip.lib.SwiftProjecting {
    internal val bundle: Bundle
    internal val displayMode: SBOMDisplayMode
    private var document: SBOMDocument?
        get() = _document.wrappedValue.sref({ this.document = it })
        set(newValue) {
            _document.wrappedValue = newValue.sref()
        }
    private var _document: skip.ui.State<SBOMDocument?> = skip.ui.State(null)
    private var loadError: String?
        get() = _loadError.wrappedValue
        set(newValue) {
            _loadError.wrappedValue = newValue
        }
    private var _loadError: skip.ui.State<String?> = skip.ui.State(null)

    constructor(bundle: Bundle, displayMode: SBOMDisplayMode = SBOMDisplayMode.hierarchy) {
        this.bundle = bundle
        this.displayMode = displayMode
    }

    override fun body(): View {
        return ComposeBuilder { composectx: ComposeContext ->
            contentView()
                .navigationTitle(LocalizedStringKey(stringLiteral = "Bill of Materials"))
                .task { -> MainActor.run { loadDocument() } }.Compose(composectx)
        }
    }

    @Composable
    @Suppress("UNCHECKED_CAST")
    override fun Evaluate(context: ComposeContext, options: Int): kotlin.collections.List<Renderable> {
        val remembereddocument by rememberSaveable(stateSaver = context.stateSaver as Saver<skip.ui.State<SBOMDocument?>, Any>) { mutableStateOf(_document) }
        _document = remembereddocument

        val rememberedloadError by rememberSaveable(stateSaver = context.stateSaver as Saver<skip.ui.State<String?>, Any>) { mutableStateOf(_loadError) }
        _loadError = rememberedloadError

        return super.Evaluate(context, options)
    }

    private fun contentView(): View {
        return ComposeBuilder { composectx: ComposeContext ->
            linvokeComposable l@{
                val matchtarget_0 = document
                if (matchtarget_0 != null) {
                    val doc = matchtarget_0
                    return@l SBOMListView(document = doc, bundle = bundle, displayMode = displayMode).Compose(composectx)
                } else {
                    val matchtarget_1 = loadError
                    if (matchtarget_1 != null) {
                        val error = matchtarget_1
                        return@l SBOMEmptyView(message = error).Compose(composectx)
                    } else {
                        return@l SBOMEmptyView(message = "No software bill of materials is available for this build.").Compose(composectx)
                    }
                }
            }
            ComposeResult.ok
        }
    }

    private suspend fun loadDocument(): Unit = Async.run {
        try {
            val doc = SBOMDocument.load(from = bundle)
            this.document = doc
        } catch (error: Throwable) {
            @Suppress("NAME_SHADOWING") val error = error.aserror()
            this.loadError = "Failed to parse software bill of materials: ${error.localizedDescription}"
        }
    }

    override fun Swift_projection(options: Int): () -> Any = Swift_projectionImpl(options)
    private external fun Swift_projectionImpl(options: Int): () -> Any

    @androidx.annotation.Keep
    companion object {

        /// Returns `true` if the given bundle contains an SBOM resource for the current platform.
        fun bundleContainsSBOM(bundle: Bundle): Boolean = SBOMDocument.resourceURL(in_ = bundle) != null
    }
}

internal class SBOMEmptyView: View {
    internal val message: String

    override fun body(): View {
        return ComposeBuilder { composectx: ComposeContext ->
            VStack(spacing = 12.0) { ->
                ComposeBuilder { composectx: ComposeContext ->
                    Image(systemName = "doc.text.magnifyingglass")
                        .font(Font.system(size = 48.0))
                        .foregroundStyle(Color.secondary).Compose(composectx)
                    Text(message)
                        .font(Font.callout)
                        .foregroundStyle(Color.secondary)
                        .multilineTextAlignment(TextAlignment.center)
                        .padding(Edge.Set.horizontal).Compose(composectx)
                    ComposeResult.ok
                }
            }
            .frame(maxWidth = Double.infinity, maxHeight = Double.infinity).Compose(composectx)
        }
    }

    constructor(message: String) {
        this.message = message
    }
}

// MARK: - List

internal class SBOMListView: View {
    internal val document: SBOMDocument
    internal val bundle: Bundle
    private var displayMode: SBOMDisplayMode
        get() = _displayMode.wrappedValue
        set(newValue) {
            _displayMode.wrappedValue = newValue
        }
    private var _displayMode: skip.ui.State<SBOMDisplayMode>

    internal constructor(document: SBOMDocument, bundle: Bundle, displayMode: SBOMDisplayMode) {
        this.document = document.sref()
        this.bundle = bundle
        this._displayMode = State(initialValue = displayMode)
    }

    /// The packages shown at the top of the list, depending on the current display mode.
    private val listedPackages: Array<SBOMPackage>
        get() {
            when (displayMode) {
                SBOMDisplayMode.hierarchy -> return document.topLevelPackages
                SBOMDisplayMode.flat -> return document.dependencyPackages
            }
        }

    override fun body(): View {
        return ComposeBuilder { composectx: ComposeContext ->
            List { ->
                ComposeBuilder { composectx: ComposeContext ->
                    // we do not show the picker on iOS because the was SBOMs are generated are always flattened (because it is derived from the Package.resolved, which does not contain any information about which packages depend on which other packages)
                    Section { ->
                        ComposeBuilder { composectx: ComposeContext ->
                            Picker(LocalizedStringKey(stringLiteral = "Display Mode"), selection = Binding({ _displayMode.wrappedValue }, { it -> _displayMode.wrappedValue = it })) { ->
                                ComposeBuilder { composectx: ComposeContext ->
                                    Text(LocalizedStringKey(stringLiteral = "Flattened")).tag(SBOMDisplayMode.flat).Compose(composectx)
                                    Text(LocalizedStringKey(stringLiteral = "Hierarchical")).tag(SBOMDisplayMode.hierarchy).Compose(composectx)
                                    ComposeResult.ok
                                }
                            }
                            .pickerStyle(PickerStyle.segmented).Compose(composectx)
                            ComposeResult.ok
                        }
                    }.Compose(composectx)

                    Section(content = { ->
                        ComposeBuilder { composectx: ComposeContext ->
                            ForEach(listedPackages) { pkg ->
                                ComposeBuilder { composectx: ComposeContext ->
                                    NavigationLink(destination = SBOMPackageDetailView(package_ = pkg, document = document)) { ->
                                        ComposeBuilder { composectx: ComposeContext ->
                                            SBOMPackageRow(package_ = pkg).Compose(composectx)
                                            ComposeResult.ok
                                        }
                                    }.Compose(composectx)
                                    ComposeResult.ok
                                }
                            }.Compose(composectx)
                            ComposeResult.ok
                        }
                    }, header = { ->
                        ComposeBuilder { composectx: ComposeContext ->
                            Text({
                                val str = LocalizedStringKey.StringInterpolation(literalCapacity = 0, interpolationCount = 0)
                                str.appendLiteral("Dependencies (")
                                str.appendInterpolation(listedPackages.count)
                                str.appendLiteral(")")
                                LocalizedStringKey(stringInterpolation = str)
                            }()).Compose(composectx)
                            ComposeResult.ok
                        }
                    }, footer = { ->
                        ComposeBuilder { composectx: ComposeContext ->
                            Text(footerText).Compose(composectx)
                            ComposeResult.ok
                        }
                    }).Compose(composectx)

                    Section(content = { ->
                        ComposeBuilder { composectx: ComposeContext ->
                            document.creationInfo?.created?.let { created ->
                                if (!created.isEmpty) {
                                    SBOMFieldRow(label = LocalizedStringKey(stringLiteral = "Created"), value = created).Compose(composectx)
                                }
                            }
                            document.creationInfo?.creators.sref()?.let { creators ->
                                if (!creators.isEmpty) {
                                    SBOMFieldRow(label = LocalizedStringKey(stringLiteral = "Generator"), value = creators.joined(separator = ", ")).Compose(composectx)
                                }
                            }
                            document.spdxVersion?.let { version ->
                                if (!version.isEmpty) {
                                    SBOMFieldRow(label = LocalizedStringKey(stringLiteral = "SPDX Version"), value = version).Compose(composectx)
                                }
                            }
                            document.dataLicense?.let { dataLicense ->
                                if (!dataLicense.isEmpty) {
                                    SBOMFieldRow(label = LocalizedStringKey(stringLiteral = "Data License"), value = dataLicense).Compose(composectx)
                                }
                            }

                            SBOMShareButton(document = document, bundle = bundle).Compose(composectx)
                            ComposeResult.ok
                        }
                    }, header = { ->
                        ComposeBuilder { composectx: ComposeContext ->
                            Text(LocalizedStringKey(stringLiteral = "About this Bill of Materials")).Compose(composectx)
                            ComposeResult.ok
                        }
                    }).Compose(composectx)
                    ComposeResult.ok
                }
            }.Compose(composectx)
        }
    }

    @Composable
    @Suppress("UNCHECKED_CAST")
    override fun Evaluate(context: ComposeContext, options: Int): kotlin.collections.List<Renderable> {
        val remembereddisplayMode by rememberSaveable(stateSaver = context.stateSaver as Saver<skip.ui.State<SBOMDisplayMode>, Any>) { mutableStateOf(_displayMode) }
        _displayMode = remembereddisplayMode

        return super.Evaluate(context, options)
    }

    private val footerText: LocalizedStringKey
        get() {
            when (displayMode) {
                SBOMDisplayMode.hierarchy -> return LocalizedStringKey(stringLiteral = "This app includes the open-source software listed above. Tap a dependency to view its license, version information, and any further dependencies it brings in.")
                SBOMDisplayMode.flat -> return LocalizedStringKey(stringLiteral = "This app includes the open-source software listed above. Tap a dependency to view its license and version information.")
            }
        }
}

internal class SBOMPackageRow: View {
    internal val package_: SBOMPackage

    override fun body(): View {
        return ComposeBuilder { composectx: ComposeContext ->
            VStack(alignment = HorizontalAlignment.leading, spacing = 4.0) { ->
                ComposeBuilder { composectx: ComposeContext ->
                    HStack(alignment = VerticalAlignment.firstTextBaseline) { ->
                        ComposeBuilder { composectx: ComposeContext ->
                            Text(package_.name ?: "Unnamed package")
                                .font(Font.headline)
                                .lineLimit(1).Compose(composectx)
                            Spacer().Compose(composectx)
                            package_.versionInfo?.let { version ->
                                if (!SPDXLicense.isUnknown(version)) {
                                    Text(version)
                                        .font(Font.caption)
                                        .foregroundStyle(Color.secondary)
                                        .lineLimit(1).Compose(composectx)
                                }
                            }
                            ComposeResult.ok
                        }
                    }.Compose(composectx)
                    package_.supplier?.let { supplier ->
                        if (!SPDXLicense.isUnknown(supplier)) {
                            Text(prettySupplier(supplier))
                                .font(Font.caption)
                                .foregroundStyle(Color.secondary)
                                .lineLimit(1).Compose(composectx)
                        }
                    }
                    package_.licenseDeclared?.let { license ->
                        if (!SPDXLicense.isUnknown(license)) {
                            Text(license)
                                .font(Font.caption2)
                                .padding(Edge.Set.horizontal, 6.0)
                                .padding(Edge.Set.vertical, 2.0)
                                .background(Color.secondary.opacity(0.15))
                                .clipShape(Capsule()).Compose(composectx)
                        }
                    }
                    ComposeResult.ok
                }
            }
            .padding(Edge.Set.vertical, 2.0).Compose(composectx)
        }
    }

    /// Strips the SPDX `Organization:` / `Person:` prefix from a supplier string.
    private fun prettySupplier(supplier: String): String {
        if (supplier.hasPrefix("Organization: ")) {
            return String(supplier.dropFirst("Organization: ".count))
        }
        if (supplier.hasPrefix("Person: ")) {
            return String(supplier.dropFirst("Person: ".count))
        }
        return supplier
    }

    constructor(package_: SBOMPackage) {
        this.package_ = package_.sref()
    }
}

// MARK: - Detail

internal class SBOMPackageDetailView: View {
    internal val package_: SBOMPackage
    internal val document: SBOMDocument

    private var browserPresented: Boolean
        get() = _browserPresented.wrappedValue
        set(newValue) {
            _browserPresented.wrappedValue = newValue
        }
    private var _browserPresented: skip.ui.State<Boolean>
    private var browserURL: URL
        get() = _browserURL.wrappedValue.sref({ this.browserURL = it })
        set(newValue) {
            _browserURL.wrappedValue = newValue.sref()
        }
    private var _browserURL: skip.ui.State<URL>

    override fun body(): View {
        return ComposeBuilder { composectx: ComposeContext ->
            List { ->
                ComposeBuilder { composectx: ComposeContext ->
                    Section(content = { ->
                        ComposeBuilder { composectx: ComposeContext ->
                            package_.name?.let { name ->
                                if (!name.isEmpty) {
                                    SBOMFieldRow(label = LocalizedStringKey(stringLiteral = "Name"), value = name).Compose(composectx)
                                }
                            }
                            package_.versionInfo?.let { version ->
                                if (!SPDXLicense.isUnknown(version)) {
                                    SBOMFieldRow(label = LocalizedStringKey(stringLiteral = "Version"), value = version).Compose(composectx)
                                }
                            }
                            package_.supplier?.let { supplier ->
                                if (!SPDXLicense.isUnknown(supplier)) {
                                    SBOMFieldRow(label = LocalizedStringKey(stringLiteral = "Supplier"), value = supplier).Compose(composectx)
                                }
                            }
                            package_.originator?.let { originator ->
                                if (!SPDXLicense.isUnknown(originator)) {
                                    SBOMFieldRow(label = LocalizedStringKey(stringLiteral = "Originator"), value = originator).Compose(composectx)
                                }
                            }
                            package_.primaryPackagePurpose?.let { purpose ->
                                if (!purpose.isEmpty) {
                                    SBOMFieldRow(label = LocalizedStringKey(stringLiteral = "Purpose"), value = purpose).Compose(composectx)
                                }
                            }
                            package_.SPDXID?.let { id ->
                                if (!id.isEmpty) {
                                    SBOMFieldRow(label = LocalizedStringKey(stringLiteral = "SPDX ID"), value = id).Compose(composectx)
                                }
                            }
                            ComposeResult.ok
                        }
                    }, header = { ->
                        ComposeBuilder { composectx: ComposeContext ->
                            Text(LocalizedStringKey(stringLiteral = "Package")).Compose(composectx)
                            ComposeResult.ok
                        }
                    }).Compose(composectx)

                    Section(content = { ->
                        ComposeBuilder { composectx: ComposeContext ->
                            package_.licenseDeclared?.let { declared ->
                                if (!SPDXLicense.isUnknown(declared)) {
                                    SBOMFieldRow(label = LocalizedStringKey(stringLiteral = "Declared"), value = resolveLicenseName(declared)).Compose(composectx)
                                }
                            }
                            package_.licenseConcluded?.let { concluded ->
                                if (!SPDXLicense.isUnknown(concluded)) {
                                    SBOMFieldRow(label = LocalizedStringKey(stringLiteral = "Concluded"), value = resolveLicenseName(concluded)).Compose(composectx)
                                }
                            }
                            package_.copyrightText?.let { copyright ->
                                if (!SPDXLicense.isUnknown(copyright)) {
                                    SBOMFieldRow(label = LocalizedStringKey(stringLiteral = "Copyright"), value = copyright).Compose(composectx)
                                }
                            }
                            package_.licenseComments?.let { comments ->
                                if (!comments.isEmpty) {
                                    SBOMFieldRow(label = LocalizedStringKey(stringLiteral = "Comments"), value = comments).Compose(composectx)
                                }
                            }
                            licensePageURL()?.let { licenseURL ->
                                Button(action = { ->
                                    this.browserURL = licenseURL
                                    this.browserPresented = true
                                }, label = { ->
                                    ComposeBuilder { composectx: ComposeContext ->
                                        Text(LocalizedStringKey(stringLiteral = "View License on spdx.org")).Compose(composectx)
                                        ComposeResult.ok
                                    }
                                }).Compose(composectx)
                            }
                            // Show extracted-license details for LicenseRef-… ids
                            extractedLicenseInfo()?.let { extracted ->
                                extracted.name?.let { name ->
                                    if (!name.isEmpty) {
                                        SBOMFieldRow(label = LocalizedStringKey(stringLiteral = "License Name"), value = name).Compose(composectx)
                                    }
                                }
                                extracted.extractedText?.let { text ->
                                    if (!text.isEmpty) {
                                        SBOMFieldRow(label = LocalizedStringKey(stringLiteral = "License Text"), value = text).Compose(composectx)
                                    }
                                }
                                extracted.seeAlsos.sref()?.let { seeAlsos ->
                                    ForEach(seeAlsos.map { it -> SBOMSeeAlsoItem(id = "seeAlso-${it}", url = it) }) { item ->
                                        ComposeBuilder { composectx: ComposeContext ->
                                            SBOMFieldRow(label = LocalizedStringKey(stringLiteral = "See Also"), value = item.url).Compose(composectx)
                                            ComposeResult.ok
                                        }
                                    }.Compose(composectx)
                                }
                            }
                            ComposeResult.ok
                        }
                    }, header = { ->
                        ComposeBuilder { composectx: ComposeContext ->
                            Text(LocalizedStringKey(stringLiteral = "License")).Compose(composectx)
                            ComposeResult.ok
                        }
                    }, footer = { ->
                        ComposeBuilder { composectx: ComposeContext ->
                            Text(LocalizedStringKey(stringLiteral = "Tap “View License on spdx.org” to read the full text of recognised open-source licenses.")).Compose(composectx)
                            ComposeResult.ok
                        }
                    }).Compose(composectx)

                    val subDependencies = document.directDependencies(of = package_)
                    if (!subDependencies.isEmpty) {
                        Section(content = { ->
                            ComposeBuilder { composectx: ComposeContext ->
                                ForEach(subDependencies) { dep ->
                                    ComposeBuilder { composectx: ComposeContext ->
                                        NavigationLink(destination = SBOMPackageDetailView(package_ = dep, document = document)) { ->
                                            ComposeBuilder { composectx: ComposeContext ->
                                                SBOMPackageRow(package_ = dep).Compose(composectx)
                                                ComposeResult.ok
                                            }
                                        }.Compose(composectx)
                                        ComposeResult.ok
                                    }
                                }.Compose(composectx)
                                ComposeResult.ok
                            }
                        }, header = { ->
                            ComposeBuilder { composectx: ComposeContext ->
                                Text({
                                    val str = LocalizedStringKey.StringInterpolation(literalCapacity = 0, interpolationCount = 0)
                                    str.appendLiteral("Dependencies (")
                                    str.appendInterpolation(subDependencies.count)
                                    str.appendLiteral(")")
                                    LocalizedStringKey(stringInterpolation = str)
                                }()).Compose(composectx)
                                ComposeResult.ok
                            }
                        }, footer = { ->
                            ComposeBuilder { composectx: ComposeContext ->
                                Text({
                                    val str = LocalizedStringKey.StringInterpolation(literalCapacity = 0, interpolationCount = 0)
                                    str.appendLiteral("These packages are pulled in transitively by ")
                                    str.appendInterpolation(package_.name ?: "this package")
                                    str.appendLiteral(".")
                                    LocalizedStringKey(stringInterpolation = str)
                                }()).Compose(composectx)
                                ComposeResult.ok
                            }
                        }).Compose(composectx)
                    }

                    package_.downloadLocation?.let { download ->
                        if (!SPDXLicense.isUnknown(download)) {
                            Section(content = { ->
                                ComposeBuilder { composectx: ComposeContext ->
                                    SBOMFieldRow(label = LocalizedStringKey(stringLiteral = "Download"), value = download).Compose(composectx)
                                    package_.homepage?.let { homepage ->
                                        if (!homepage.isEmpty) {
                                            SBOMFieldRow(label = LocalizedStringKey(stringLiteral = "Homepage"), value = homepage).Compose(composectx)
                                        }
                                    }
                                    package_.description?.let { description ->
                                        if (!description.isEmpty) {
                                            SBOMFieldRow(label = LocalizedStringKey(stringLiteral = "Description"), value = description).Compose(composectx)
                                        }
                                    }
                                    package_.summary?.let { summary ->
                                        if (!summary.isEmpty) {
                                            SBOMFieldRow(label = LocalizedStringKey(stringLiteral = "Summary"), value = summary).Compose(composectx)
                                        }
                                    }
                                    ComposeResult.ok
                                }
                            }, header = { ->
                                ComposeBuilder { composectx: ComposeContext ->
                                    Text(LocalizedStringKey(stringLiteral = "Source")).Compose(composectx)
                                    ComposeResult.ok
                                }
                            }).Compose(composectx)
                        }
                    }

                    package_.externalRefs.sref()?.let { refs ->
                        if (!refs.isEmpty) {
                            Section(content = { ->
                                ComposeBuilder { composectx: ComposeContext ->
                                    ForEach(refs.indices.map { it -> SBOMIndexedItem(id = "ref-${it}", index = it) }) { item ->
                                        ComposeBuilder { composectx: ComposeContext ->
                                            SBOMExternalRefRow(ref = refs[item.index]).Compose(composectx)
                                            ComposeResult.ok
                                        }
                                    }.Compose(composectx)
                                    ComposeResult.ok
                                }
                            }, header = { ->
                                ComposeBuilder { composectx: ComposeContext ->
                                    Text(LocalizedStringKey(stringLiteral = "External References")).Compose(composectx)
                                    ComposeResult.ok
                                }
                            }).Compose(composectx)
                        }
                    }

                    package_.checksums.sref()?.let { checksums ->
                        if (!checksums.isEmpty) {
                            Section(content = { ->
                                ComposeBuilder { composectx: ComposeContext ->
                                    ForEach(checksums.indices.map { it -> SBOMIndexedItem(id = "checksum-${it}", index = it) }) { item ->
                                        ComposeBuilder { composectx: ComposeContext ->
                                            SBOMChecksumRow(checksum = checksums[item.index]).Compose(composectx)
                                            ComposeResult.ok
                                        }
                                    }.Compose(composectx)
                                    ComposeResult.ok
                                }
                            }, header = { ->
                                ComposeBuilder { composectx: ComposeContext ->
                                    Text(LocalizedStringKey(stringLiteral = "Checksums")).Compose(composectx)
                                    ComposeResult.ok
                                }
                            }).Compose(composectx)
                        }
                    }
                    ComposeResult.ok
                }
            }
            .navigationTitle(package_.name ?: "Package")
            .openWebBrowser(isPresented = Binding({ _browserPresented.wrappedValue }, { it -> _browserPresented.wrappedValue = it }), url = browserURL, mode = WebBrowserMode.embeddedBrowser(params = null)).Compose(composectx)
        }
    }

    @Composable
    @Suppress("UNCHECKED_CAST")
    override fun Evaluate(context: ComposeContext, options: Int): kotlin.collections.List<Renderable> {
        val rememberedbrowserPresented by rememberSaveable(stateSaver = context.stateSaver as Saver<skip.ui.State<Boolean>, Any>) { mutableStateOf(_browserPresented) }
        _browserPresented = rememberedbrowserPresented

        val rememberedbrowserURL by rememberSaveable(stateSaver = context.stateSaver as Saver<skip.ui.State<URL>, Any>) { mutableStateOf(_browserURL) }
        _browserURL = rememberedbrowserURL

        return super.Evaluate(context, options)
    }

    private fun licensePageURL(): URL? {
        SPDXLicense.licensePageURL(for_ = package_.licenseDeclared)?.let { url ->
            return url.sref()
        }
        return SPDXLicense.licensePageURL(for_ = package_.licenseConcluded)
    }

    /// Looks up an extracted license info entry if the package's `licenseDeclared`
    /// or `licenseConcluded` is a `LicenseRef-…` identifier.
    private fun extractedLicenseInfo(): SBOMExtractedLicense? {
        val candidates = arrayOf(package_.licenseDeclared, package_.licenseConcluded)
        for (candidate in candidates.sref()) {
            val id_0 = candidate
            if ((id_0 == null) || !id_0.hasPrefix("LicenseRef-")) {
                continue
            }
            document.extractedLicense(forId = id_0)?.let { info ->
                return info.sref()
            }
        }
        return null
    }

    /// If the given license id is a `LicenseRef-…`, return its human-readable name when available.
    private fun resolveLicenseName(license: String): String {
        if (license.hasPrefix("LicenseRef-")) {
            document.extractedLicense(forId = license)?.let { info ->
                info.name?.let { name ->
                    if (!name.isEmpty) {
                        return "${name} (${license})"
                    }
                }
            }
        }
        return license
    }

    private constructor(package_: SBOMPackage, document: SBOMDocument, browserPresented: Boolean = false, browserURL: URL = URL(string = "https://spdx.org/licenses/"), privatep: Nothing? = null) {
        this.package_ = package_.sref()
        this.document = document.sref()
        this._browserPresented = skip.ui.State(browserPresented)
        this._browserURL = skip.ui.State(browserURL.sref())
    }

    constructor(package_: SBOMPackage, document: SBOMDocument): this(package_ = package_, document = document, privatep = null) {
    }
}

internal class SBOMExternalRefRow: View {
    internal val ref: SBOMExternalRef

    override fun body(): View {
        return ComposeBuilder { composectx: ComposeContext ->
            VStack(alignment = HorizontalAlignment.leading, spacing = 2.0) { ->
                ComposeBuilder { composectx: ComposeContext ->
                    ref.referenceType?.let { type ->
                        if (!type.isEmpty) {
                            Text(type)
                                .font(Font.caption)
                                .foregroundStyle(Color.secondary).Compose(composectx)
                        }
                    }
                    ref.referenceLocator?.let { locator ->
                        if (!locator.isEmpty) {
                            Text(locator)
                                .font(Font.footnote).Compose(composectx)
                        }
                    }
                    ComposeResult.ok
                }
            }
            .padding(Edge.Set.vertical, 2.0).Compose(composectx)
        }
    }

    constructor(ref: SBOMExternalRef) {
        this.ref = ref.sref()
    }
}

internal class SBOMChecksumRow: View {
    internal val checksum: SBOMChecksum

    override fun body(): View {
        return ComposeBuilder { composectx: ComposeContext ->
            VStack(alignment = HorizontalAlignment.leading, spacing = 2.0) { ->
                ComposeBuilder { composectx: ComposeContext ->
                    checksum.algorithm?.let { alg ->
                        if (!alg.isEmpty) {
                            Text(alg)
                                .font(Font.caption)
                                .foregroundStyle(Color.secondary).Compose(composectx)
                        }
                    }
                    checksum.checksumValue?.let { value ->
                        if (!value.isEmpty) {
                            Text(value)
                                .font(Font.system(Font.TextStyle.footnote, design = Font.Design.monospaced))
                                .lineLimit(1)
                                .truncationMode(Text.TruncationMode.middle).Compose(composectx)
                        }
                    }
                    ComposeResult.ok
                }
            }
            .padding(Edge.Set.vertical, 2.0).Compose(composectx)
        }
    }

    constructor(checksum: SBOMChecksum) {
        this.checksum = checksum.sref()
    }
}

// MARK: - ForEach helper items
//
// SwiftUI's `List` becomes a Compose `LazyColumn` on Android. Multiple `ForEach`
// blocks inside the same `List` share a single key namespace, so using `\.offset`
// or array indices in more than one `ForEach` causes a Compose
// `IllegalArgumentException: Key "0" was already used` crash when the list is
// scrolled. These small `Identifiable` wrappers give each row a globally unique
// string id within the enclosing list.

internal class SBOMSeeAlsoItem: Identifiable<String> {
    override val id: String
    internal val url: String

    constructor(id: String, url: String) {
        this.id = id
        this.url = url
    }

    override fun equals(other: Any?): Boolean {
        if (other !is SBOMSeeAlsoItem) return false
        return id == other.id && url == other.url
    }

    override fun hashCode(): Int {
        var result = 1
        result = Hasher.combine(result, id)
        result = Hasher.combine(result, url)
        return result
    }
}

internal class SBOMIndexedItem: Identifiable<String> {
    override val id: String
    internal val index: Int

    constructor(id: String, index: Int) {
        this.id = id
        this.index = index
    }

    override fun equals(other: Any?): Boolean {
        if (other !is SBOMIndexedItem) return false
        return id == other.id && index == other.index
    }

    override fun hashCode(): Int {
        var result = 1
        result = Hasher.combine(result, id)
        result = Hasher.combine(result, index)
        return result
    }
}

// MARK: - Shared row helpers

internal class SBOMFieldRow: View {
    internal val label: LocalizedStringKey
    internal val value: String

    override fun body(): View {
        return ComposeBuilder { composectx: ComposeContext ->
            VStack(alignment = HorizontalAlignment.leading, spacing = 2.0) { ->
                ComposeBuilder { composectx: ComposeContext ->
                    Text(label)
                        .font(Font.caption)
                        .foregroundStyle(Color.secondary).Compose(composectx)
                    Text(value)
                        .font(Font.callout).Compose(composectx)
                    ComposeResult.ok
                }
            }
            .padding(Edge.Set.vertical, 2.0).Compose(composectx)
        }
    }

    constructor(label: LocalizedStringKey, value: String) {
        this.label = label
        this.value = value
    }
}

// MARK: - Share

internal class SBOMShareButton: View {
    internal val document: SBOMDocument
    internal val bundle: Bundle

    override fun body(): View {
        return ComposeBuilder { composectx: ComposeContext ->
            sbomText()?.let { text ->
                ShareLink(item = text, subject = Text(LocalizedStringKey(stringLiteral = "Software Bill of Materials")), message = Text(document.name ?: "SBOM")) { ->
                    ComposeBuilder { composectx: ComposeContext ->
                        Label(LocalizedStringKey(stringLiteral = "Share Bill of Materials"), systemImage = "square.and.arrow.up").Compose(composectx)
                        ComposeResult.ok
                    }
                }.Compose(composectx)
            }
            ComposeResult.ok
        }
    }

    /// Returns the raw SPDX JSON text for the bundle's SBOM, if available, falling back to
    /// re-encoding the parsed `document` if the original bytes cannot be read.
    private fun sbomText(): String? {
        SBOMDocument.rawData(from = bundle)?.let { data ->
            String(data = data, encoding = StringEncoding.utf8)?.let { s ->
                return s
            }
        }
        val encoder = JSONEncoder()
        encoder.outputFormatting = JSONEncoder.OutputFormatting.of(JSONEncoder.OutputFormatting.prettyPrinted, JSONEncoder.OutputFormatting.sortedKeys)
        (try { encoder.encode(document) } catch (_: Throwable) { null })?.let { data ->
            String(data = data, encoding = StringEncoding.utf8)?.let { s ->
                return s
            }
        }
        return null
    }

    constructor(document: SBOMDocument, bundle: Bundle) {
        this.document = document.sref()
        this.bundle = bundle
    }
}
 // !SKIP_BRIDGE // !SKIP_BRIDGE
