// ----------------------------------------------------------------
// Local stand-in for the `skip-build-plugin` shipped with the Skip CLI.
// Generated by `skip export` so the exported project builds on a host
// without Skip installed; functionally equivalent to SkipBuildPlugin in
// skipstone's PluginCommand.swift, but reads Skip.env directly without
// invoking the Skip toolchain.
//
// The script name registers this as a precompiled script plugin with id
// `skip-build-plugin`, satisfying the `id("skip-build-plugin")` request
// in Android/app/build.gradle.kts.
// ----------------------------------------------------------------
import java.util.Properties
import org.gradle.api.GradleException
import org.gradle.kotlin.dsl.withGroovyBuilder

// Empty marker extension so the user's `skip { }` block compiles. Mirrors
// the SkipBuildExtension type defined by the upstream plugin.
interface SkipBuildExtension
extensions.create("skip", SkipBuildExtension::class.java)

val skipEnv = Properties().apply {
    val skipEnvFile = rootDir.parentFile.resolve("Skip.env")
    require(skipEnvFile.isFile) {
        "Required Skip.env file is missing at ${skipEnvFile}"
    }
    skipEnvFile.reader(Charsets.UTF_8).use(::load)
    // Skip.env uses xcconfig `//` line comments; java.util.Properties
    // parses them as a single empty key, so drop it.
    remove("//")
}

fun lookupSkipEnv(key: String): String =
    skipEnv.getProperty(key)
        ?: System.getProperty("SKIP_${key}")
        ?: throw GradleException(
            "Required key '${key}' is not set in Skip.env or system property SKIP_${key}")

// `android { namespace = group as String }` in the user's build.gradle.kts
// requires `group` to be the Android package name.
project.group = lookupSkipEnv("ANDROID_PACKAGE_NAME")

// AGP's android {} extension is registered before this precompiled plugin
// is applied (the app build.gradle.kts lists com.android.application before
// `id("skip-build-plugin")` in its plugins block), so we can configure it
// immediately using the Groovy builder DSL to avoid a compile-time
// dependency on AGP types in buildSrc.
//
// Note: precompiled script plugins delegate properties through the
// script class, so `withGroovyBuilder` must be called on the project
// explicitly rather than through the implicit receiver.
project.withGroovyBuilder {
    getProperty("android").withGroovyBuilder {
        getProperty("defaultConfig").withGroovyBuilder {
            val applicationId = (skipEnv.getProperty("ANDROID_APPLICATION_ID")
                ?: lookupSkipEnv("PRODUCT_BUNDLE_IDENTIFIER")).replace("-", "_")
            setProperty("applicationId", applicationId)
            setProperty("versionCode", lookupSkipEnv("CURRENT_PROJECT_VERSION").toInt())
            setProperty("versionName", lookupSkipEnv("MARKETING_VERSION"))
            getProperty("manifestPlaceholders").withGroovyBuilder {
                for ((rawKey, rawValue) in skipEnv) {
                    val key = rawKey.toString()
                    if (key.isNotBlank()) {
                        setProperty(key, rawValue.toString())
                    }
                }
            }
        }
    }
}

dependencies {
    // The transpiled app module is included as a sibling project; see
    // `include(":<PRODUCT_NAME>")` in ../settings.gradle.kts.
    add("implementation", project(":${lookupSkipEnv("PRODUCT_NAME")}"))
}