// Generated by `skip export` to register the local
// `skip-build-plugin` precompiled script plugin.
plugins {
    `kotlin-dsl`
}

repositories {
    mavenCentral()
    google()
    gradlePluginPortal()
}