// build.gradle.kts generated by Skip for Sudoku
dependencies {
    implementation(platform("com.squareup.okhttp3:okhttp-bom:5.3.2"))
    implementation("com.squareup.okhttp3:okhttp")
    implementation("org.commonmark:commonmark:0.28.0")
    implementation("org.commonmark:commonmark-ext-gfm-strikethrough:0.28.0")
    testImplementation(testLibs.json)
    api(platform(libs.kotlin.bom))
    compileOnly(testLibs.kotlin.test)
    compileOnly(testLibs.kotlin.test.junit)
    api(testLibs.androidx.test.runner)
    api(testLibs.kotlinx.coroutines.test)
    api(testLibs.kotlin.test.junit)
    testImplementation(testLibs.asm)
    testImplementation(testLibs.robolectric)
    testImplementation(testLibs.androidx.test.core)
    testImplementation(testLibs.androidx.test.rules)
    testImplementation(testLibs.androidx.test.ext.junit)
    androidTestImplementation(testLibs.androidx.test.core)
    androidTestImplementation(testLibs.androidx.test.rules)
    androidTestImplementation(testLibs.androidx.test.ext.junit)
    api(project(":FaireGamesModel"))
    api(project(":SkipModel"))
    api(project(":SkipFoundation"))
    api(project(":SkipLib"))
    testImplementation(project(":SkipUnit"))
    androidTestImplementation(project(":SkipUnit"))
    api(project(":SkipKit"))
    api(project(":SkipUI"))
    api(project(":AppFairUI"))
}

plugins {
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.android.library)
    id("maven-publish")
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.serialization)
}

android {
    namespace = group as String
    compileSdk = libs.versions.android.sdk.compile.get().toInt()
    defaultConfig {
        minSdk = libs.versions.android.sdk.min.get().toInt()
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        testInstrumentationRunnerArguments["disableAnalytics"] = "true"
    }
    compileOptions {
        sourceCompatibility = JavaVersion.toVersion(libs.versions.jvm.get())
        targetCompatibility = JavaVersion.toVersion(libs.versions.jvm.get())
    }
    testOptions {
        unitTests {
            isIncludeAndroidResources = true
        }
    }
    publishing {
        multipleVariants {
            allVariants()
            withSourcesJar()
        }
    }
    buildFeatures {
    }
}

tasks.withType<Test>().configureEach {
    systemProperties.put("robolectric.logging", "stdout")
    systemProperties.put("robolectric.graphicsMode", "NATIVE")
    testLogging {
        showStandardStreams = true
    }
    filter {
        isFailOnNoMatchingTests = false
        excludeTestsMatching("NonExistingExcludePattern")
    }
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinJvmCompile>() {
    compilerOptions {
        suppressWarnings = true
        jvmTargetValidationMode = org.jetbrains.kotlin.gradle.dsl.jvm.JvmTargetValidationMode.WARNING
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget(libs.versions.jvm.get().toString())
    }
}

publishing {
    publications {
        register<MavenPublication>("default") {
            groupId = project.group.toString()
            artifactId = project.name
            version = project.version.toString()
            afterEvaluate { from(components["default"]) }
        }
    }
}
