// This is the top-level Gradle settings generated for the Skip project.
// The module dependencies it contains may be symbolic links to peer folders.
//
// This file is generated by the Skip transpiler plugin and is
// derived from the aggregate Skip/skip.yml files from the SPM project.
// Edits made directly to this file will be lost.
//
// Open with External Editor to build and run this project in an IDE.
//
dependencyResolutionManagement {
    versionCatalogs {
        create("libs") {
            version("androidx-compose-bom", "2026.03.01")
            library("androidx-compose-bom", "androidx.compose", "compose-bom").versionRef("androidx-compose-bom")
            library("androidx-compose-runtime", "androidx.compose.runtime", "runtime").withoutVersion()
            library("kotlin-reflect", "org.jetbrains.kotlin", "kotlin-reflect").withoutVersion()
            version("jvm", "17")
            version("android-sdk-min", "28")
            version("android-sdk-compile", "36")
            version("android-gradle-plugin", "8.13.2")
            plugin("android-library", "com.android.library").versionRef("android-gradle-plugin")
            plugin("android-application", "com.android.application").versionRef("android-gradle-plugin")
            version("kotlin", "2.3.0")
            plugin("kotlin-android", "org.jetbrains.kotlin.android").versionRef("kotlin")
            plugin("kotlin-compose", "org.jetbrains.kotlin.plugin.compose").versionRef("kotlin")
            library("kotlin-bom", "org.jetbrains.kotlin", "kotlin-bom").versionRef("kotlin")
            version("kotlin-coroutines", "1.10.2")
            library("kotlinx-coroutines-core", "org.jetbrains.kotlinx", "kotlinx-coroutines-core").versionRef("kotlin-coroutines")
            library("kotlinx-coroutines-android", "org.jetbrains.kotlinx", "kotlinx-coroutines-android").versionRef("kotlin-coroutines")
            version("coil", "3.4.0")
            version("androidx-nav3", "1.0.1")
            version("kotlinx-serialization-json", "1.8.1")
            version("androidx-appcompat", "1.7.1")
            version("androidx-activity", "1.13.0")
            version("androidx-lifecycle-process", "2.10.0")
            version("androidx-material3-adaptive", "1.2.0")
            version("androidx-work", "2.11.1")
            library("androidx-core-ktx", "androidx.core", "core-ktx").withoutVersion()
            library("androidx-compose-ui", "androidx.compose.ui", "ui").withoutVersion()
            library("androidx-compose-ui-tooling", "androidx.compose.ui", "ui-tooling").withoutVersion()
            library("androidx-compose-animation", "androidx.compose.animation", "animation").withoutVersion()
            library("androidx-compose-material", "androidx.compose.material", "material").withoutVersion()
            library("androidx-compose-material3", "androidx.compose.material3", "material3").withoutVersion()
            library("androidx-compose-material-icons-extended", "androidx.compose.material", "material-icons-extended").withoutVersion()
            library("androidx-compose-foundation", "androidx.compose.foundation", "foundation").withoutVersion()
            library("androidx-appcompat", "androidx.appcompat", "appcompat").versionRef("androidx-appcompat")
            library("androidx-appcompat-resources", "androidx.appcompat", "appcompat-resources").versionRef("androidx-appcompat")
            library("androidx-navigation3-runtime", "androidx.navigation3", "navigation3-runtime").versionRef("androidx-nav3")
            library("androidx-navigation3-ui", "androidx.navigation3", "navigation3-ui").versionRef("androidx-nav3")
            library("kotlinx-serialization-json", "org.jetbrains.kotlinx", "kotlinx-serialization-json").versionRef("kotlinx-serialization-json")
            plugin("kotlin-serialization", "org.jetbrains.kotlin.plugin.serialization").versionRef("kotlin")
            library("androidx-activity-compose", "androidx.activity", "activity-compose").versionRef("androidx-activity")
            library("androidx-lifecycle-process", "androidx.lifecycle", "lifecycle-process").versionRef("androidx-lifecycle-process")
            library("androidx-compose-material3-adaptive", "androidx.compose.material3.adaptive", "adaptive").versionRef("androidx-material3-adaptive")
            library("androidx-compose-material3-adaptive-navigation-suite", "androidx.compose.material3", "material3-adaptive-navigation-suite").versionRef("androidx-material3-adaptive")
            library("androidx-work-runtime", "androidx.work", "work-runtime-ktx").versionRef("androidx-work")
            library("coil-compose", "io.coil-kt.coil3", "coil-compose").versionRef("coil")
            library("coil-network-okhttp", "io.coil-kt.coil3", "coil-network-okhttp").versionRef("coil")
            library("coil-svg", "io.coil-kt.coil3", "coil-svg").versionRef("coil")
            library("androidx-compose-ui-test", "androidx.compose.ui", "ui-test").withoutVersion()
            library("androidx-compose-ui-test-junit4", "androidx.compose.ui", "ui-test-junit4").withoutVersion()
            library("androidx-compose-ui-test-manifest", "androidx.compose.ui", "ui-test-manifest").withoutVersion()
        }
        create("testLibs") {
            library("json", "org.json", "json").version("20251224")
            version("androidx-test", "1.6.1")
            library("androidx-test-runner", "androidx.test", "runner").versionRef("androidx-test")
            library("androidx-test-core", "androidx.test", "core").versionRef("androidx-test")
            library("androidx-test-rules", "androidx.test", "rules").versionRef("androidx-test")
            version("androidx-test-ext-junit", "1.3.0")
            library("androidx-test-ext-junit", "androidx.test.ext", "junit").versionRef("androidx-test-ext-junit")
            version("kotlin-coroutines-test", "1.10.2")
            library("kotlinx-coroutines-test", "org.jetbrains.kotlinx", "kotlinx-coroutines-test").versionRef("kotlin-coroutines-test")
            library("kotlin-test", "org.jetbrains.kotlin", "kotlin-test").withoutVersion()
            library("kotlin-test-junit", "org.jetbrains.kotlin", "kotlin-test-junit").withoutVersion()
            version("robolectric", "4.16.1")
            library("robolectric", "org.robolectric", "robolectric").versionRef("robolectric")
            version("asm", "9.10")
            library("asm", "org.ow2.asm", "asm").versionRef("asm")
        }
    }
    repositories {
        mavenCentral()
        google()
    }
}

pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        google()
    }
}

rootProject.name = "org.appfair.app.fairegames.ui"
include(":FaireGames")
project(":FaireGames").projectDir = file("FaireGames")
include(":FaireGamesModel")
project(":FaireGamesModel").projectDir = file("FaireGamesModel")
include(":SkipModel")
project(":SkipModel").projectDir = file("SkipModel")
include(":SkipFoundation")
project(":SkipFoundation").projectDir = file("SkipFoundation")
include(":SkipLib")
project(":SkipLib").projectDir = file("SkipLib")
include(":SkipUnit")
project(":SkipUnit").projectDir = file("SkipUnit")
include(":SkipKit")
project(":SkipKit").projectDir = file("SkipKit")
include(":SkipUI")
project(":SkipUI").projectDir = file("SkipUI")
include(":BlockBlast")
project(":BlockBlast").projectDir = file("BlockBlast")
include(":AppFairUI")
project(":AppFairUI").projectDir = file("AppFairUI")
include(":Tetris")
project(":Tetris").projectDir = file("Tetris")
include(":FlappyBird")
project(":FlappyBird").projectDir = file("FlappyBird")
include(":Breakout")
project(":Breakout").projectDir = file("Breakout")
include(":Sudoku")
project(":Sudoku").projectDir = file("Sudoku")
include(":TwentyFortyEight")
project(":TwentyFortyEight").projectDir = file("TwentyFortyEight")
include(":Drop7")
project(":Drop7").projectDir = file("Drop7")
